### ISSUE TITLE
`tCall` ってどんなメソッドなんですか？

### ISSUE THREAD

**Issue by kazuma1989** [tail-island/barium#1]
https://github.com/tail-island/barium/blob/b9ff50df2e12e5a5e25ef6630f53c716ace5390d/src/game.js#L189

**Comment by kazuma1989** [comment]
定義も見つからず、この行の直前直後で console.log を挟んでも、そんな変数ないってエラーになるので、とても気になります

**Comment by tail-island** [comment]
Clojureのスレッディングマクロ（->や->>）と同じ機能で、
https://github.com/tail-island/babel-plugin-lajureの中でbabelの機能を使って実現しています。tCall(f(1),
g(2), h(3))とすると、h(3, g(2,
f(1)))に転換されます。最初の引数を実行した結果を、2つ目の関数の引数に追加して実行した結果を、3つ目の関数の…（繰り返し）…という処理です。

ECMAScriptで提案されているパイプライン演算子と似ていますけど、引数が追加になる点で異なっています。

http://tyano.shelfinc.com/post/76007113565/threadingmacros
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Pipeline_operator
https://qiita.com/erukiti/items/0c6154e7ca7ad51f19ff

**Comment by kazuma1989** [comment]
なるほど、回答ありがとうございました。
わかりづらいので、改善希望です。
